language: php
php:
  - 5.6
  - 5.3

services:
  - redis-server

before_script:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - phpenv rehash

script:
  - vendor/bin/phpunit --verbose --colors
