nginx:
  build: nginx/
  links:
    - php-fpm
  ports:
    - 8080:80

php-fpm:
  build: .
  volumes:
    - .:/var/www/html
  links:
    - redis
  environment:
    - REDIS_HOST=redis

redis:
  image: redis
  ports:
      - 6379:6379
